name: Linter Test

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
      
    steps:
      - name: Cloning Repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install Node dependencies
        run: npm install

      - name: Run Linter - eslintrc
        run: npm run lint
